###################### Spring configurations ################################
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    username: root
    password: 123456professor?
    database: gmsofficemgtdb
    url: jdbc:mysql://localhost:3306/gmsofficemgtdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 465
    username: sundayluckyenyinnadeveloper@gmail.com #talk2wahab247@gmail.com
    password: ksmrokaolwsjvznc #xqllqmrlgmsslixp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true


########################## Password Encryption Configuration ############################
gms:
  security:
    jwt:
      secret: c1zJs5rugZn2nTcavvIs45QPmFMCjYnyc1zJs5rugZn2nTca
      expirationInMinutes: 30
  otp:
    signup:
      expirationTimeInMin: 10