###################### Spring & Datasource configurations ################################
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    host: 173.254.28.210
    port: 3306
    username: thycorpi_blnusers
    password: 9R0oAmjM0vsx
    database: thycorpi_bln
    url: jdbc:mysql://173.254.28.210:3306/thycorpi_bln
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Mysql8Dialect
    hibernate:
          ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 465
    username: sundayluckyenyinnadeveloper@gmail.com #talk2wahab247@gmail.com
    password: ksmrokaolwsjvznc #xqllqmrlgmsslixp
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true


########################## Password Encryption Configuration ############################
gms:
  security:
    jwt:
      secret: c1zJs5rugZn2nTcavvIs45QPmFMCjYnyc1zJs5rugZn2nTca
      expirationInMinutes: 30
  otp:
    signup:
      expirationTimeInMin: 10

  wallet:
    digit: 10

############################### Configuration for SILA API ##############################
third-party:
  sila:
    app-name: gms-sila
    public-name: sure-trade-sila
    app-handle: gms-sila
    client-id: -0vDi1GOXCTMMGaTvyTgKirzKoLtPxjDMNcNRskbsgg
    client-secret: 4cI9pJsmUx15fMvYxLtzxrMY5BOwvOJvaTmXZlrd5m_UbMrPg44QAPM8rCktxI-y56LpBhgtnoJrRJbSIM1hDA
    token-url: https://sandbox.silamoney.com/0.2/auth_token
    version: 0.2
    auth-handle: gms-sila
