########################################### Spring & Datasource configurations ################################
spring:
  config:
    import: optional:file:env-prod.properties

  datasource:
    driver-class-name: ${DATABASE_DRIVER_CLASS_NAME}
    host: ${DATABASE_HOST_NAME}
    port: ${DATABASE_PORT}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    database: ${DATABASE_BASE_SCHEMA}
    url: ${DATABASE_URL}

  jpa:
    properties:
      hibernate:
        dialect: ${DATABASE_DIALECT}
    hibernate:
      ddl-auto: update



  ############################################### Configuration for Mail ############################################
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true



########################## Password Encryption Configuration ############################
gms:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expirationInMinutes: ${JWT_EXP_IN_MINUTE}
  otp:
    signup:
      expirationTimeInMin: ${OTP_EXPIRATION_IN_MIN}
  base-url: ${ALQUIMIA_PAY_BASE_URL}
  #  base-url: http://localhost:3000
  wallet:
    digit: 10

  transaction:
    fee:
      percent: 3

  deposit:
    cheque:
      fee:
        percent: 5

  admin:
    email: ${ADMIN_EMAILS}


third-party:

  ################################################ Circle configurations #################################
  circle:
    base-url: ${CIRCLE_BASE_URL}
    api-key: ${CIRCLE_API_KEY}
    master-account:
      base:
        account-number: ${CIRCLE_BASE_ACCOUNT_NUMBER}
        routing-number: ${CIRCLE_ROUTING_NUMBER}
        billing-details:
          name: NNNNNNNN
          city: Boston
          line1: 100 Money Street
          line2: Suite 1
          postalCode: 01234
          district: MA
          country: US
        bank-address:
          country: US
          bank-name: SAN FRANCISCO
          city: SAN FRANCISCO
          line1: 100 Money Street
          line2: Suite 1
          district: CA


  ################################ Configuration for Alquimia Pay ####################################
  alquimia:
    blockchain:
      address: ${ALQUIMIA_BLOCKCHAIN_ADDRESS}
    account:
      account-number: ${ALQUIMIA_BUSINESS_ACCOUNT_NUMBER}
      account-type: ${ALQUIMIA_BUSINESS_ACCOUNT_TYPE}
    user:
      login: ${ALQUIMIA_USER_LOGIN}
      password: ${ALQUIMIA_USER_PASSWORD}
    remittance:
      submit-order-url: ${ALQUIMIA_ORDER_SUBMISSION_API}
      beneficiary:
        default-address: ${ALQUIMIA_BENEFICIARY_DEFAULT_ADDRESS}
        default-city: ${ALQUIMIA_BENEFICIARY_DEFAULT_CITY}


  ################################## Configuration for XE Exchange Rate #################################
  xe:
    app-id: ${XE_APP_ID}
    app-key: ${XE_APP_KEY}
    base-url: ${XE_BASE_URL}


############################################### Configuration for logging #########################################
logging:
  file:
    path: logs
    name: logs/alquimia_pay.log


############################################### Configuration for Admin #########################################
security:
  admin:
    allowed-login-count: 3



############################################## Configuration for FTP ###########################################
ftp:
  remote:
    host-name: NNNNNN
    port: 21
    username: NNNNNN
    password: password

    azure:
      account-name: ${AZURE_FTP_ACCOUNT_NAME}
      endpoint: ${AZURE_FTP_ENDPOINT}
      account-key: ${AZURE_FTP_ACCOUNT_KEY}


  local:
    temp-dir: temp_dir
